apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opentext
type: Opaque
stringData:
  POSTGRES_DB: otdsdb
  POSTGRES_USER: otdsuser
  POSTGRES_PASSWORD: otdspassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otds-postgresql
  namespace: opentext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otds-postgresql
  template:
    metadata:
      labels:
        app: otds-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:13
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: otds-postgresql
  namespace: opentext
spec:
  selector:
    app: otds-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
