{{- if .Values.otdsdb.automaticDatabaseCreation.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "initdb.script" . }}
{{- if and .Values.migration.enabled .Values.migration.preUpgradeJob.enabled .Release.IsUpgrade}}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
{{- if .Values.global.namespace }}
    "meta.helm.sh/release-namespace": {{ .Values.global.namespace }}
{{- else }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
{{- end }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
{{- end }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/init-db.sh").AsConfig | indent 2 }}
{{- end }}