{{- $customsecretname := default .Values.global.existingSecret .Values.customSecretName -}}
{{- if and .Values.enabled (not $customsecretname) (not .Values.vault.enabled) }}

########################################################################
# OpenText Directory Services (OTDS) Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "otdsws.name" . }}-secrets
{{- if and .Values.migration.enabled .Values.migration.preUpgradeJob.enabled .Release.IsUpgrade}}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
{{- if .Values.global.namespace }}
    "meta.helm.sh/release-namespace": {{ .Values.global.namespace }}
{{- else }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
{{- end }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
{{- end }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTDS_JAKARTA_PERSISTENCE_JDBC_USER: {{ required "A valid otdsws.otdsdb.username is required!" .Values.otdsdb.username | b64enc }}
  OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD: {{ required "A valid otdsws.otdsdb.password is required!" .Values.otdsdb.password | b64enc }}
  OTDS_DIRECTORY_BOOTSTRAP_INITIALPASSWORD: {{ default "" ( default .Values.otadminPassword .Values.adminPassword ) | b64enc }}
{{- if .Values.adminEmail }}
  OTDS_DIRECTORY_BOOTSTRAP_INITIALUSEREMAIL: {{ .Values.adminEmail | b64enc }}
{{- end }}
{{- if .Values.isBizAdmin }}
  OTDS_DIRECTORY_BOOTSTRAP_INITIALUSERBIZADMIN: {{ "true" | b64enc }}
{{- end }}
  OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET: {{ required "A valid otdsws.cryptKey is required!" .Values.cryptKey | b64enc }}
{{- if and .Values.migration.enabled (not .Values.migration.usingLegacyImage) (not .Values.migration.preUpgradeJob.enabled)}}
  OTDS_DIRECTORY_BOOTSTRAP_PASSWORD: {{ required "A valid otdsws.migration.password is required!" .Values.migration.password | b64enc }}
{{- end }}
{{- if .Values.otdsdb.automaticDatabaseCreation.enabled }}
  OTDS_DB_ADMIN_PASSWORD: {{ required "A valid otdsws.otdsdb.automaticDatabaseCreation.dbAdminPassword is required!" .Values.otdsdb.automaticDatabaseCreation.dbAdminPassword | b64enc }}
{{- end }}
---

{{- end }}
