{{- if eq .Values.enabled true }}
{{- if eq .Values.kerberos.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "otdsws.name" . }}-kerberos
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
data:
{{- if .Values.kerberos.keytabFile }}
  krb5kt: |-
    {{ .Values.kerberos.keytabFile | b64enc }}
{{- if .Values.kerberos.configFile }}
  krb5.conf: |-
    {{ .Values.kerberos.configFile | b64enc }}
{{- end }}
{{- else }}
    {{ range $path, $_ :=  .Files.Glob  "config/kerberos/krb5*" }}
    {{ $subdir := dir $path }}
    {{ $currentFilename := ($path | replace (printf "%s/" $subdir) "" ) }}
    {{ $currentFilename | indent 2 }}: |-
        {{ tpl ($.Files.Get $path) $ | b64enc }}
    {{ end }}
{{- end }}
{{- end }}
{{- end }}
