{{- $customsecretname := default .Values.global.existingSecret .Values.customSecretName -}}
{{- if and (not $customsecretname) (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: migrate-job-secrets
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OTDS_JAKARTA_PERSISTENCE_JDBC_USER: {{ required "A valid otdsws.otdsdb.username is required!" .Values.otdsdb.username | b64enc }}
  OTDS_JAKARTA_PERSISTENCE_JDBC_PASSWORD: {{ required "A valid otdsws.otdsdb.password is required!" .Values.otdsdb.password | b64enc }}
{{- if and .Values.migration.enabled (not .Values.migration.usingLegacyImage) }}
  OTDS_DIRECTORY_BOOTSTRAP_PASSWORD: {{ required "A valid otdsws.migration.password is required!" .Values.migration.password | b64enc }}
  OTDS_DIRECTORY_BOOTSTRAP_CRYPTSECRET: {{ required "A valid otdsws.cryptKey is required!" .Values.cryptKey | b64enc }}
{{- end }}
---

{{- end }}